/**
 * Centralised authorization helpers.
 *
 * Single source of truth for "is this caller an admin?" so the fail-open bug
 * cannot reappear in one handler after being fixed in another.
 *
 * Policy (fail-CLOSED):
 *   - `ADMINS` MUST contain at least one numeric Telegram ID.
 *     If it is missing or contains no valid IDs, NOBODY is an admin and every
 *     admin action is denied. A misconfigured deployment must not become an
 *     open door.
 *   - When `GROUP_ID` is set, admin actions are only accepted from that chat.
 *
 * Note on Telegram: inline-keyboard `callback_data` is generated by the bot,
 * but a message carrying an inline keyboard can be *forwarded*, and clicking a
 * button in a forwarded message still delivers a callback_query to the bot with
 * the clicker's ID. Therefore every privileged callback MUST re-check
 * authorization server-side — it can never be inferred from the fact that the
 * button "came from" the admin chat.
 */

/**
 * Parse the ADMINS environment variable into a clean array of numbers.
 * Malformed entries are dropped rather than crashing the process.
 *
 * @returns {number[]}
 */
export function getAdminIds() {
  const raw = process.env.ADMINS || "";
  return raw
    .split(",")
    .map((id) => id.trim())
    .filter((id) => id.length > 0)
    .map((id) => Number(id))
    .filter((id) => Number.isFinite(id));
}

/**
 * Is the given Telegram user ID configured as an admin?
 * Fails closed when no admins are configured.
 *
 * @param {number|string} userId
 * @returns {boolean}
 */
export function isAdminUser(userId) {
  const adminIds = getAdminIds();
  if (adminIds.length === 0) return false;
  return adminIds.includes(Number(userId));
}

/**
 * Is the given chat the configured admin group?
 * When GROUP_ID is unset this returns false (fail-closed).
 *
 * @param {number|string} chatId
 * @returns {boolean}
 */
export function isAdminGroup(chatId) {
  const groupId = process.env.GROUP_ID;
  if (!groupId) return false;
  return String(chatId) === String(groupId);
}

/**
 * Full admin check used by every privileged callback: the caller must be a
 * configured admin AND (when GROUP_ID is configured) acting from that group.
 *
 * @param {number|string} chatId
 * @param {number|string} userId
 * @returns {boolean}
 */
export function isAdmin(chatId, userId) {
  if (!isAdminUser(userId)) return false;
  if (process.env.GROUP_ID && !isAdminGroup(chatId)) return false;
  return true;
}

export default { getAdminIds, isAdminUser, isAdminGroup, isAdmin };
